### ISSUE TITLE
KeyErrors on simulator prefix with libraries that use other loggers

### ISSUE THREAD

**Issue by operatingops** [operatingops/python_prod_script_pattern#4]
For example, using boto3 to list S3 buckets like this:
```python
import boto3
client = boto3.client('s3')
client.list_buckets()
```

You'll get errors like this:
```shell
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'prefix'
```

The core problem is likely that `logging.basicConfig()` operates on the root logger but we only add the `SimulatorFilter` to the module-level logger. The format string set by `basicConfig` on the root logger expects the `prefix` string (even if it's empty), but the filter that sets it only exists on the module logger.

It's possible this is a signal that we're abusing the logging filter system. It's really designed for making the levels more granular, not for adding informative text to the output.

**Comment by operatingops** [comment]
Using filters this way isn't an anti-pattern: https://docs.python.org/3/howto/logging-cookbook.html#using-filters-to-impart-contextual-information
